language: minimal

services:
  - docker

env:
  - FL_NIX_IMAGE: ${CI_REGISTRY}/fretlink/nix-overlay:2.2.1-channel-19.03-v2019-04-29-debian

cache:
  directories:
  - .psc-package
  - output

script:
  - docker pull ${FL_NIX_IMAGE}
  - docker run --rm ${FL_NIX_IMAGE} /bin/bash "nix-shell --run 'make ci'"
